spring:
  datasource:
    url: jdbc:mysql://12.123.123.12:3306/web_mysql01?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: aaaa
    password: aaaaaa
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 12.123.123.12
    port: 6379
    password: 123456
    client-type: jedis
#开启支持put,delete请求
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
      ## table-prefix: le_ 设置前缀
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #配置日志  数据库前缀可以不用配置
    map-underscore-to-camel-case: true          #开启驼峰命名规则，与pojo层字段对应


server:
  port: 9898